// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package foo_bar

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type Simple struct {
	One uint8
	_io *kaitai.Stream
	_root *Simple
	_parent kaitai.Struct
}
func NewSimple() *Simple {
	return &Simple{
	}
}

func (this Simple) IO_() *kaitai.Stream {
	return this._io
}

func (this *Simple) Read(io *kaitai.Stream, parent kaitai.Struct, root *Simple) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.One = tmp1
	return err
}
