version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: cat /dev/null | sbt compile compilerJVM/stage fastOptJS buildNpmJsFile compilerJVM/universal:packageBin
      - store_artifacts:
          path: jvm/target/universal/kaitai-struct-compiler-*.zip
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
  test:
    <<: *defaults
    steps:
      - run: cat /dev/null | sbt test
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
